### ISSUE TITLE
counts for pkcg03 plot should be per cohorts

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tlg-catalog#131]
### Discussed in https://github.com/insightsengineering/tlg-catalog/discussions/130

<div type='discussions-op-text'>

<sup>Originally posted by **giscus[bot]** September 22, 2023</sup>
# tlg-catalog/graphs/pharmacokinetic/pkcg03

Plot of Mean PK Concentration Over Time by Cohort

https://insightsengineering.github.io/tlg-catalog/graphs/pharmacokinetic/pkcg03.html

</div>

**Comment by legrasv** [comment]
I had to hardcode the function g_lineplot it for one of my TLGs:

    # df_N <- as.data.frame(table(alt_counts_df[[strata]], exclude = c(NA, NaN, Inf))) # nolint
    df_N <- aggregate(USUBJID ~ eval(parse(text = strata)), data = alt_counts_df, FUN = function(x) length(unique(x))) # nolint
    
    knowing that USUBJID has to be defined in the parameters of the function somehow

**Comment by Melkiades** [comment]
> A bit of code to help:
> 
> I had to hardcode the function g_lineplot it for one of my TLGs:
> 
> ```r
> # df_N <- as.data.frame(table(alt_counts_df[[strata]], exclude = c(NA, NaN, Inf))) # nolint
> df_N <- aggregate(USUBJID ~ eval(parse(text = strata)), data = alt_counts_df, FUN = function(x) length(unique(x))) # nolint
> ```
> 
> knowing that USUBJID has to be defined in the parameters of the function somehow

@ayogasekaram could you take a look at this, please? Thank you!!! :)

**Comment by legrasv** [comment]
@ayogasekaram Actually on this plot, there is something else that is wrong:
<img width="559" alt="image" src="https://github.com/insightsengineering/tlg-catalog/assets/99191912/a707afd5-3267-442f-8118-2090ac7518db">
It does not link all the points (because of the different nominal time that we have between the Treatment groups).

So I could also fix it myself by adding in g_lineplot :
  df_stats <- df_stats[!is.na(df_stats$mean),] ## could be coded in dplyr as well
  
  before the line of code:
  
    ##################################################
  ## Prepare certain plot's properties.
  ##################################################

**Comment by legrasv** [comment]
Result:
<img width="598" alt="image" src="https://github.com/insightsengineering/tlg-catalog/assets/99191912/54a6a32b-5894-45cf-9955-219e177c15fe">

**Comment by ayogasekaram** [comment]
thank you @legrasv for your code suggestions! I believe your second suggestion is already implemented in g_lineplot [here](https://github.com/insightsengineering/tern/blob/0861b91f02298d6f06fefd39427d965a0bf38fbe/R/g_lineplot.R#L213). the default for the `mid` variable is "mean" which is identical to the line of code you have above.

**Comment by legrasv** [comment]
Sounds good thank you

**Comment by legrasv** [comment]
Hello

@ayogasekaram @Melkiades 
Could you please update the code of matches variable so that it works for this case:
It was show on the legend plot Day 1 Day 10 Day 5 :/

  ```
df_N = data.frame(AVISIT = factor(c("Day 1", "Day 10", "Day 5")))
levels(df_N$AVISIT) = c("Day 1", "Day 5", "Day 10")

group_var = "AVISIT"

strata_N <- paste0(group_var, "_N") # nolint
df_N[[strata_N]] <- paste0(df_N[[group_var]], " (N = 1)") # nolint
```
levels(df_N$AVISIT)
[1] "Day 1"  "Day 5"  "Day 10"

```
keep strata factor levels

matches <- sapply(unique(df_N[[group_var]]), function(x) {
    +   regex_pattern <- gsub("([][(){}^$.|*+?\\\\])", "\\\\\\1", x)
    +   unique(df_N[[paste0(group_var, "_N")]])[grepl(
      +     paste0("^", regex_pattern),
      +     unique(df_N[[paste0(group_var, "_N")]])
      +   )]
    + })

print(matches)
```
[[1]]
[1] "Day 1 (N = 1)"  "Day 10 (N = 1)"

[[2]]
[1] "Day 5 (N = 1)"

[[3]]
[1] "Day 10 (N = 1)"




**The code below works well**
```
matches <- sapply(unique(df_N[[group_var]]), function(x) {
    +   regex_pattern <- gsub("([][(){}^$.|*+?\\\\])", "\\\\\\1", x)
    +   search_strings[grepl(
      +     paste0("^", regex_pattern, "\\b"),
      +     search_strings
      +   )]
    + })

print(matches)
```
[1] "Day 1 (N = 1)"  "Day 5 (N = 1)"  "Day 10 (N = 1)"

**Comment by ayogasekaram** [comment]
Hey @legrasv! thank you for letting me know - I can work on making the update in tern. Quick question: is search_strings in your preferred code a custom function?

**Comment by legrasv** [comment]
@ayogasekaram Sorry I forgot to add that:

	search_strings <- unique(df_N[[strata_N]])

**Comment by Shaakon35** [comment]
@ayogasekaram the \\b was an issue in case the group column contained special characters (like "("), I therefore changed the function to: 

```
    # keep strata factor levels
	matches <- sapply(levels(df_N[[group_var]]), function(x) {
	  regex_pattern <- gsub("([][(){}^$.|*+?\\\\])", "\\\\\\1", x)
	  search_strings[grepl(
	    paste0("^", regex_pattern, " \\(N = "),
	    search_strings
	  )]
	})
	
	if (length(unlist(matches)) != length(search_strings)) {
	  stop("Error: Group legend with (N=) has not been successfully matched.")
	}
```

changing " \\(N = "), and adding a check on the length.

Please update the function when you have time, thank you so much!
