### ISSUE TITLE
[Bug]: ylim not an argument in g_km for KMG01

### ISSUE THREAD

**Issue by Nolan-Steed** [insightsengineering/tlg-catalog#135]
### What happened?

Get an error when using the default argument `ylim = c(0,1)`
![image](https://github.com/insightsengineering/tlg-catalog/assets/56098440/46816351-fb9a-4713-867d-a2cef703e5ac)

This argument isn't found within the help documentation and the error goes away when I remove it

### Relevant log output

library(tern)
library(scda)
library(dplyr)
library(nestcolor)

syn_adtte <- synthetic_cdisc_dataset("latest", "adtte")
anl <- syn_adtte %>%
  dplyr::filter(PARAMCD == "OS") %>%
  dplyr::mutate(is_event = CNSR == 0)
variables <- list(tte = "AVAL", is_event = "is_event", arm = "ARMCD")

plot <- g_km(
  df = anl,
  variables = variables,
  xlab = "Time (Days)",
  ylim = c(0, 1),
  annot_coxph = TRUE
)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by pawelru** [comment]
@insightsengineering/nest-sme can you provide a feedback. This should be easy to fix.

**Comment by clarkliming** [comment]
no error from my side, @Nolan-Steed could you please check you package versions?

**Comment by edelarua** [comment]
@Nolan-Steed I'm not sure why the parameter is not appearing in the documentation (I can look into that) - but you can see it in the function code [here](https://github.com/insightsengineering/tern/blob/HEAD/R/kaplan_meier_plot.R#L29) and it should be in as of tern v0.8.5 (July 23) coming from [this PR](https://github.com/insightsengineering/tern/pull/1001).

**Comment by Nolan-Steed** [comment]
Thanks for looking into this. I realized that I am using tern v0.8.4 so that is the issue. I will close this.
