### ISSUE TITLE
[Bug]: Error in AET04 example

### ISSUE THREAD

**Issue by Nolan-Steed** [insightsengineering/tlg-catalog#147]
### What happened?

I am wondering if `.indent_mods` be `indent_mod` in the `summarize_num_patients` arguments. I get an error that says, unused argument but this is resolved with updating to `indent_mod`. The documentation also supports this change. 

![image](https://github.com/insightsengineering/tlg-catalog/assets/56098440/4e7694a2-f00f-4da2-b689-c5961cc44665)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by edelarua** [comment]
Hi @Nolan-Steed,

We are in the process of deprecating the `indent_mod` argument in `tern` functions and renaming to the `.indent_mods` argument instead. Depending on your version of `tern`, you may not have the `.indent_mods` argument available - it was introduced in all analyze/summarize functions in `tern v0.8.2.9005` (see [the latest documentation for `summarize_num_patients`](https://insightsengineering.github.io/tern/main/reference/summarize_num_patients.html?q=summarize_num#ref-usage)).

**Comment by Nolan-Steed** [comment]
HI @edelarua I see thank you for clarifying this!
