### ISSUE TITLE
Fix `teal` apps

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/tlg-catalog#16]
- [x] https://github.com/insightsengineering/tlg-catalog/issues/204
- [x] https://github.com/insightsengineering/tlg-catalog/issues/205
- [x] https://github.com/insightsengineering/tlg-catalog/issues/206
- [x] https://github.com/insightsengineering/tlg-catalog/issues/207
- [x] https://github.com/insightsengineering/tlg-catalog/issues/208
- [ ] tables/efficacy/mmrmt01.html -> this awaits clicking "calculate" button - maybe it's possible to register a click (and wait some more time as this is probably the longest calculation)
- [ ] graphs/efficacy/mmrmg01.html -> (same as above mmrmt01)

This is valid at the moment of ~creating this issue~ last update. Please double-check whether this list if complete and modify if needed.

**Comment by Nolan-Steed** [comment]
Hi @pawelru I think the core dev team might have to tackle this see [Issue 754](https://github.com/insightsengineering/teal.modules.clinical/issues/745)

**Comment by pawelru** [comment]
please consult with @lcd2yyz and @donyunardi if the core dev team has a bandwith thanks!

**Comment by shajoezhu** [comment]
This design was delibrite, due to the computational time

**Comment by pawelru** [comment]
I have gone through the list again and a lot of errors have been resolved in the meantime. There are only few left for which we have a hard crash and greyed out screen.

**Comment by pawelru** [comment]
Hey @shajoezhu do you think it would be worth to include this in pre-release preps for tmc? This could potentially detect errors in modules (or it could be just a bad app code - IDK yet).

**Comment by shajoezhu** [comment]
Hi @pawelru , I think it is worth doing, however our time and resources are cutting short for the release this month, we can target to complete this by the next release (in two months). what do you think?

**Comment by pawelru** [comment]
perhaps core dev teal could help? do you guys have a bandwidth? @donyunardi

**Comment by donyunardi** [comment]
Probably not this week as we are still trying to push teal.transform to the finish line.
We will be better positioned to help out on sprint 3 and 4 if that works.

**Comment by pawelru** [comment]
It seems that I forgot about this issue and just done this all :)
Closing

**Comment by m7pr** [comment]
That's the hero we need :)
