### ISSUE TITLE
Allow stable / devel via quarto conditional content

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/tlg-catalog#192]
The current state of code is working only for devel mode and stable is red for a while. I have been thinking how to allow both stable and devel profile on the same codebase (and avoid creating separate stable and devel git branches that we already agreed it would be difficult to maintain) and I came up with quarto [conditional content based on profile used](https://quarto.org/docs/projects/profiles.html#profile-content). 

This summarise into more or less this:
```
::: {.content-visible when-profile="stable"}
pkg::foo_deprecated(...)
:::

::: {.content-visible when-profile="development"}
pkg::bar
:::
```

Then after release of a given package we will remove stable and make devel unconditional. We have to include this check in our release template. We might help ourselves and provide additional comments what packages are affected.

Please assess if it would make sense in our case and if yes - please implement so that we will have both stable and devel passing. Please also correct min version of dependent packages as per stable and not devel.

**Comment by edelarua** [comment]
Hi @pawelru,
This seems like a great solution!
I have reverted the package dependencies to the latest released version of each but some of the changes that have been made since the releases (mainly the teal module fixes) will need to be reverted and converted to use this method to fix the catalog rendering. 
Since the DESCRIPTION file lists package dependencies for the stable version, is the devel version automated to use the latest development versions of each package dependency instead of the specified versions?

**Comment by pawelru** [comment]
> Since the DESCRIPTION file lists package dependencies for the stable version, is the devel version automated to use the latest development versions of each package dependency instead of the specified versions?

Yes - that's correct. For each _profile_ we install appropriate versions of nest packages before rendering. For devel profile we are using [staged deps](https://github.com/insightsengineering/tlg-catalog/blob/cc0c8f1d1a2ba02c39777033acb77067d67ef7d4/.github/workflows/docs.yml#L47-L54) and for stable - [r-universe](https://github.com/insightsengineering/tlg-catalog/blob/cc0c8f1d1a2ba02c39777033acb77067d67ef7d4/.github/workflows/docs.yml#L152-L156).

> some of the changes that have been made since the releases (mainly the teal module fixes) will need to be reverted and converted to use this method to fix the catalog rendering.

That's exactly what I was thinking of. We need to correct these articles to support both stable and devel. This does not neccessarily means _full revert_ but rather _restore_ removed/changed codes and have both versions supported.

**Comment by pawelru** [comment]
If it happens that this is no longer needed because teal packages will be released (hence a new stable version) then please just document this for the future

**Comment by edelarua** [comment]
This was resolved after the last CRAN releases, with the method detailed [above](https://github.com/insightsengineering/tlg-catalog/issues/192#issue-2070855376) used to resolve these issues since.
