### ISSUE TITLE
Move KMG01 from "Graphs - Other" to "Graphs - Efficacy"?

### ISSUE THREAD

**Issue by zhux63** [insightsengineering/tlg-catalog#195]
### What is your question?

Hi NEST TLGC team,
I noticed that the current [KMG01 template](https://insightsengineering.github.io/tlg-catalog/stable/graphs/other/kmg01.html) is listed under "Graphs - Other", instead of "Graphs - Efficacy". Would it be better if it's listed under "Graphs - Efficacy"? Please ignore my question if the team is already aware of this. Many thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by shajoezhu** [comment]
Good call! thanks @zhux63 for reporting this.

**Comment by martincadek** [comment]
Proposed solution here: https://github.com/insightsengineering/tlg-catalog/pull/229

**Comment by martincadek** [comment]
Proposed solution here: https://github.com/insightsengineering/tlg-catalog/pull/234
