### ISSUE TITLE
Replace avalu parameter with avalu_var 

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tlg-catalog#199]
tmc changes in https://github.com/insightsengineering/teal.modules.clinical/pull/940

tm_g_ipp.R
tm_t_exposure.R
tm_t_pp_laboratory.R

**Comment by edelarua** [comment]
FYI @ayogasekaram - to prevent failures on the stable version of tlg-c from these updates, follow the procedure outlined by Pawel [here](https://github.com/insightsengineering/tlg-catalog/issues/192#issue-2070855376) and then after the release we can merge the two sections.

**Comment by ayogasekaram** [comment]
Modules either don't code for `avalu` or are already coded as `avalu_var`. No changes required.
