### ISSUE TITLE
[Bug]: `FSTG01` and `FSTG02` apps are broken

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/tlg-catalog#208]
### What happened?

https://insightsengineering.github.io/tlg-catalog/development/graphs/efficacy/fstg01.html
https://insightsengineering.github.io/tlg-catalog/development/graphs/efficacy/fstg02.html

### Relevant log output

```
Warning: Error in : only 'grobs' allowed in "gList" 
 when evaluating qenv code:
p <- decorate_grob(g_forest(tbl = result, col_symbol_size = NULL), titles = "Forest Plot of Best Overall Response for BESRSPI: Best Confirmed Overall Response by Investigator", footnotes = "", gp_footnotes = grid::gpar(fontsize = 12))
```

```
Warning: Error in : only 'grobs' allowed in "gList" 
 when evaluating qenv code:
p <- decorate_grob(g_forest(tbl = result, col_symbol_size = NULL), titles = c("Forest Plot of Survival Duration for OS: Overall Survival", "Stratified by STRATA2"), footnotes = "", gp_footnotes = grid::gpar(fontsize = 12))
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by edelarua** [comment]
This is resolved by https://github.com/insightsengineering/teal.modules.clinical/pull/925
