### ISSUE TITLE
Add Negative Binomial example to the `RATET01` template

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/tlg-catalog#21]
Depends on https://github.com/insightsengineering/tern/issues/857

To do:
- [x] Add a new "customized table 2" tab in [main/book/tables/efficacy/ratet01.qmd](https://github.com/insightsengineering/tlg-catalog/blob/main/book/tables/efficacy/ratet01.qmd?rgh-link-date=2024-01-09T08%3A41%3A18Z) and add a negative binomial example there

**Comment by duanx9** [comment]
current location: https://github.com/insightsengineering/tlg-catalog/blob/main/book/tables/efficacy/ratet01.qmd
