### ISSUE TITLE
Find and implement alternative of `ggpubr` package

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/tlg-catalog#245]
This package is not currently on r-wasm repo (https://repo.r-wasm.org/) which makes the code not executable in web-r. Currently there are only a few use-cases of this: https://github.com/search?q=repo%3Ainsightsengineering%2Ftlg-catalog%20ggpubr&type=code

**Comment by edelarua** [comment]
We should be able to replace `ggpubr` with the equivalent `cowplot` functions for each of these use cases.
