### ISSUE TITLE
[Feature Request]: Request for TLG catalog page interface

### ISSUE THREAD

**Issue by shino-iwase** [insightsengineering/tlg-catalog#265]
### Feature description

I have a request for [the TLG catalog page](https://insightsengineering.github.io/tlg-catalog/stable/) interface. I think it can be more convenient if "Standard Table/Listing" tab is shown at first, instead of "Data Setup" tab as it is encouraged to use this page to communicate with stakeholders who are not familiar with programing code.
Thank you for your support.
Shino

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by edelarua** [comment]
This could be implemented quite easily if we'd like to do so (see [cardinal](https://pharmaverse.github.io/cardinal/) where a similar format was used), but then the question becomes at which position the "Data Setup" tab should appear when multiple table variants exist (after the "Standard Table" and before other variants, after all table variants, etc.)

**Comment by shajoezhu** [comment]
Thanks @shino-iwase for the suggestion, the initial purpose of tlg-c was for education, and show case what nest packages can do, and gathers simple examples how to do it. it is very interesting that you mention that you use this communicate with stakeholders, would you mind elaborating more on how you doing this? if it is beneficial for more users, we certainly would love to incorporate this as an enhancement. @khatril @telepath37 @pawelru fyi

**Comment by ddsjoberg** [comment]
FWIW, every time I am browsing the catalog, I click to the table to see what it looks like. Then I look at the code **IF** it is indeed the table I am looking for (i don't have the table IDs memorized)

**Comment by shajoezhu** [comment]
I see what you mean @ddsjoberg @shino-iwase , yes, I think we can definitely improve this and hide the data setup step a bit more. 

This is a much improved version, I completely agree! back in the day, the catalog was a very long lengthy rmd, and you don't see the table until you scrolled down to the very bottom. I wanted to make it like a real catalog, like a food recipe, you see the picture first, then dive into the ingredients. 

I like @edelarua suggested cardinal approach.

another quick fix we could do is probably drop the "data setup" tab completely, and have two collapsed code section under standard table tab. @pawelru @khatril

**Comment by shino-iwase** [comment]
Thank you all for prompt reply!

@shajoezhu, I insert the hyperlink to each template into LoPO so that clinical team can find what output looks. To use tNEST {chevron} catalog and TLG-Catalog for TLG layouts is encouraged in [standard TLG file](https://gdsr.roche.com/ui/gdsr-browser-app%23GDSRBrowser#/da). For this purpose, I think it is beneficial if all the templates that are defined in the TLG file are included in the TLG catalog page even if code doesn't exist. Currently we need to use both the TLG Catalog page and TLG standard file (word file, such as [Disposition, Demography and Safety Standard Tables](https://gdsr.roche.com/resource/gdsr.roche.com/release/products/dataAnalysis/GDS_Standard_TLG_Specs_Tables_1.docx),[Standard Listings and Graphs](https://gdsr.roche.com/resource/gdsr.roche.com/release/products/dataAnalysis/GDS_Standard_TLG_Specs_Listings_Graphs.docx) ) .

@edelarua , @shajoezhu , I am not familiar with the structure of this page, but I think the idea that @shajoezu suggested works. In addition, it looks that the code included in "Data Setup" tab are also included in ">_Try this using WebR" tab in each table tab. 

In addition, I would like to request to add "tab" URL for each tab so that we can make hyperlink to specific tab when multiple table variants exist and we want to refer non-Standard table.  I hope the following page help to explain what I mean.
https://stackoverflow.com/questions/76159867/using-url-hash-to-open-page-on-specific-tab.

**Comment by shino-iwase** [comment]
Thank you for updating! Now I can see tables first.

**Comment by pawelru** [comment]
You welcome! And thanks to you for reaching out with this. It's much better now. It's a pity we haven't noticed this earlier 🙃
