### ISSUE TITLE
fix R CMD CHECK notes

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tlg-catalog#272]
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  tests/testthat/_book/assets/www/.gitkeep
  tests/testthat/_book/assets/www/lock/.gitkeep
  tests/testthat/_data/.rbuildkeep
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.
* checking for portable file names ... NOTE
Found the following non-portable file paths:
  tlg.catalog.pkg/tests/testthat/_book/_extensions/coatless/webr/qwebr-document-engine-initialization.js
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/css/latex-fontsize.css
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-brands-400.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-brands-400.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-regular-400.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-regular-400.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-solid-900.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-solid-900.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-v4compatibility.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-v4compatibility.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Brands-Regular-400.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Brands-Regular-400.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Free-Regular-400.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Free-Regular-400.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Free-Solid-900.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Free-Solid-900.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/shinylive/resources/css/shinylive-quarto.css

**Comment by pawelru** [comment]
All in all - I don't think these notes could be solved - or I don't have a good idea how to do this. May I ask you why this brought your attention. These should not fail our CI.

Please have a look at the current error:
```
ERROR: NotFound: No such file or directory (os error 2): lstat '/__w/tlg-catalog/tlg-catalog/tlg.catalog.pkg.Rcheck/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/css/all.css'
```

If you build-ignore some of the quarto extension files then these won't be added to the .tar.gz bundle. Then we are running tests on the .tar.gz bundle. During tests we are re-generating the whole book to compare the snapshots. If files are missing then quarto process complains.

That's just one mechanism. There is also a `tests/testthat/_data/.rbuildkeep` file which name indicates not to ignore it. During the tests - we are writting the files. We want to write it to some dir. The role of that dummy empty file is just to keep the dir not empty. If it's empty - you are going to see another note during R CMD BUILD (see last entry):
```
* checking for empty or unneeded directories
Removed empty directory ‘tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts’
Removed empty directory ‘tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets’
Removed empty directory ‘tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/shinylive/resources’
Removed empty directory ‘tlg.catalog.pkg/tests/testthat/_book/assets/www/lock’
Removed empty directory ‘tlg.catalog.pkg/tests/testthat/_book/assets/www’
Removed empty directory ‘tlg.catalog.pkg/tests/testthat/_data’
```

**Comment by shajoezhu** [comment]
these was raised as notes in our integration test
