### ISSUE TITLE
[bug] mmrmg01 not rendering 

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tlg-catalog#285]
https://insightsengineering.github.io/tlg-catalog/stable/graphs/efficacy/mmrmg01.html

**Comment by edelarua** [comment]
@shajoezhu this is just a minor mix up coming from moving the data setup section to the end of the template. 

Fixed here: https://github.com/insightsengineering/tlg-catalog/pull/286

**Comment by shajoezhu** [comment]
Thanks @edelarua , lets keep monitoring 

https://insightsengineering.github.io/tlg-catalog/development/graphs/efficacy/mmrmg01.html

**Comment by pawelru** [comment]
I'm currently working on some wider changes in tlg-catalog and I got it already sorted out. Let me wrap up my stuff and today I will submit a PR
