### ISSUE TITLE
Update COXT* templates after refactoring `summarize_coxreg`

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/tlg-catalog#35]
See https://github.com/insightsengineering/tern/issues/841.

**Comment by duanx9** [comment]
I found the variable "arm" inconsistency when I prepared the chevron template for coxt02 where `ARM` got releveled with the `"B: Placebo"` being the first level while in the later Cox regression analysis `ARMCD` (yet to be releveled) was actually the one being used, which leads to the reference arm inconsistent with what has been done in the data preprocessing.

I was about to start by creating an issue to echo that but it seems the fix has been well covered by the referred PRs here. So just type in here if everyone occurs the same...

![image](https://user-images.githubusercontent.com/114642081/233885494-cd161668-2466-4711-8631-7bc7972b855c.png)
