### ISSUE TITLE
[Bug]: AET02 sorting based on synthetic data

### ISSUE THREAD

**Issue by barnett11** [insightsengineering/tlg-catalog#41]
### What happened?

I believe the below code is too specific to the synthetic data scenario, 
```r
result <- result %>%
  prune_table() %>% 
  sort_at_path( 
    path = c("AEBODSYS"), 
    scorefun = cont_n_onecol(4) 
  ) 
```

Should this be instead,
```r
result <- result %>%
      prune_table() %>%
      sort_at_path(
        path =  c("AEBODSYS"),
        scorefun = cont_n_allcols,
        decreasing = TRUE
      ) 
```

### Relevant log output

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
I analyzed a bit the problem and I am not sure about this. How this works is a bit complicated. So what the two sortings do here are the following:

- `cont_n_onecol(4)` sorts the *row summaries* by taking the last column (which is the All column). This is highlighted in orange in fig 1. Changing this to all columns would do exactly the same by adding also the other count elements from the same line.
- `score_occurences` sorts the row values by summing all counts. These are at a lower row level, indicated by different colors, which are different sorting in fig
![Screenshot 2023-04-26 143301](https://user-images.githubusercontent.com/11279768/234576953-dd2247c6-7c4b-4276-b4f4-a11be3b65368.png)

Now it is possible to replace with `cont_n_allcols` the instances of `cont_n_onecol(4)` but it would not change the results. Of course, this covers only cases where the referenced column is all column, and in aet02 it seems not to be different. Let me know what you think @barnett11

**Comment by barnett11** [comment]
My concern sorry @Melkiades is that `cont_n_onecol(4)` is very specific to this test data, if i copy this code into my study and I have two treatment groups, or six treatment groups, I'll get an undesired result will I not?

**Comment by Melkiades** [comment]
> My concern sorry @Melkiades is that `cont_n_onecol(4)` is very specific to this test data, if i copy this code into my study and I have two treatment groups, or six treatment groups, I'll get an undesired result will I not?

ahhh it makes sense indeed. Just a question: do they all have "All" column or is it dependent on the study?

**Comment by barnett11** [comment]
It is dependent on study - the actual default template would not have an "All" column

**Comment by Melkiades** [comment]
I found this also in cmt01 and aet09. Shall I modify them too?

**Comment by barnett11** [comment]
Yes I would think the same is needed thankyou
