### ISSUE TITLE
aet01_aesi is not having correction indetions through white spaces

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tlg-catalog#55]
https://insightsengineering.github.io/tlg-catalog/tables/adverse-events/aet01_aesi.html

linked to https://github.com/insightsengineering/rtables/issues/630

**Comment by edelarua** [comment]
Since the corresponding `rtables` issue has not yet been resolved I can temporarily fix this in tlg-c via repeated `count_patients_with_flags` calls. Once the whitespace issue has been addressed we can revert to the solution that utilizes this.
