### ISSUE TITLE
reorganize tlg entries

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tlg-catalog#57]
# TODO 

Reorg the tlg-C by following catagories

Demography
Disposition
Medical History
Exposure
Con Med
AE
Deaths
Laboratory
Vital Signs
ECG

See https://github.com/insightsengineering/tlg-catalog/issues/57#issuecomment-1628499700 for details

# Original message
demographic table and disposition table should not be grouped into safety. maybe we should use another label to group them, like "study population"

**Comment by shajoezhu** [comment]
Let's follow-up in the G-lopo, and see how they are catagorized.

**Comment by khatril** [comment]
So, Demog, Disposition categories would come under "Across Therapeutic Area Safety" which is the overall term for the domains below:
Demography
Disposition
Medical History
Concomitant Medication
Deaths
AE
Labs

I don't believe it is wrong, however, TLG-C could specify the domains under the 'Safety' category but we would also have to include AE and labs here for consistency.

**Comment by clarkliming** [comment]
I don't think this is the correct way to categorize these entries. demographics and dispositions are not only for safety assessment, but also for efficacy assessment. 

In addition, if we really want to group demographics and disposition into safety output, why we separate ae and lab?

Please reconsider this

![image](https://github.com/insightsengineering/tlg-catalog/assets/36079400/ce0bac0b-96ab-4361-9486-7822b25302e9)

**Comment by clarkliming** [comment]
maybe @barnett11 can comment here

**Comment by shajoezhu** [comment]
I had checked with two stats before, and both thought our current catagories were not ideal, hence they suggested to sperate them out and use Glopo as for reference.

**Comment by barnett11** [comment]
The categories used by the standard Safety LoPO currently are below,
Demography
Disposition
Medical History
Exposure
Con Med
AE
Deaths
Laboratory
Vital Signs
ECG
